name: Development GitHub Pages

on:
  push: 
    branches: ["*"]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install
      # - run: npm run test
      - run: npm run build
      - run: |
          git config --global user.email "marcos.vcg.ads@gmail.com"
          git config --global user.name "marcos-vcg"
          npm run deploy
